# Project: MyHook
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = ../obj/myhook_private.res
OBJ  = ../obj/KeyLogger.o ../obj/myhook.o $(RES)
LINKOBJ  = ../obj/KeyLogger.o ../obj/myhook.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include"  -I"core"  -I"logtypes" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"core"  -I"logtypes" 
BIN  = ../bin/MyHook.exe
CXXFLAGS = $(CXXINCS)   -DWINVER=0x0501
CFLAGS = $(INCS)   -DWINVER=0x0501
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ../bin/MyHook.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "..\bin\MyHook.exe" $(LIBS)

../obj/KeyLogger.o: core/KeyLogger.cpp core/KeyLogger.h core/LogType.h   C:/Dev-Cpp/include/windows.h C:/Dev-Cpp/include/stdio.h   C:/Dev-Cpp/include/sys/types.h
	$(CPP) -c core/KeyLogger.cpp -o ../obj/KeyLogger.o $(CXXFLAGS)

../obj/myhook.o: core/myhook.cpp C:/Dev-Cpp/include/c++/3.4.2/cstdlib   C:/Dev-Cpp/include/windows.h C:/Dev-Cpp/include/time.h   C:/Dev-Cpp/include/c++/3.4.2/string core/LogType.h core/KeyLogger.h   logtypes/Debug.h core/LogType.h C:/Dev-Cpp/include/c++/3.4.2/iostream   logtypes/LocalFile.h
	$(CPP) -c core/myhook.cpp -o ../obj/myhook.o $(CXXFLAGS)

../obj/myhook_private.res: myhook_private.rc ../src/Resources.rc 
	$(WINDRES) -i myhook_private.rc --input-format=rc -o ../obj/myhook_private.res -O coff  --include-dir ../res --include-dir ../res/icons
